version: '3.3'
services:
    client:
        container_name: letterboard-client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: letterboard-client:dev
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
    server:
        container_name: letterboard-server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: letterboard-server:dev
        volumes:
            - './server:/app'
            - '/app/node_modules'
        ports:
            - '3001:3001'
        environment: 
            - NODE_ENV=development
            - HOST=0.0.0.0
        depends_on: 
            - redis
    redis:
        container_name: redis-json
        image: redislabs/rejson:latest
        ports:
            - '6379:6379'